name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # גרסת Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build --if-present

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.PAT_TOKEN }}  # שימוש בטוקן אישי
          branch: gh-pages
          folder: dist/checkout-app
